apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-storage
        peristentVolumeClaim:
          claimName: redis-pvc-jegan #Replace 'jegan' with your name

      containers:
      - image: bitnami/redis:latest
        name: redis

        env:
        - name: REDIS_PASSWORD
          value: root@123

      volumeMounts:
      - name: redis-storage
        mountPath: /bitnami/redis/data
