apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan #Replace 'jegan' with your name
  labels:
    name: jegan #Replace 'jegan' with your name
    tier: be
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 #Replace this IP with your linux server IP
    path: /var/nfs/jegan/mysql #Replace /var/nfs/user02/mysql
