apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-{{.Values.pv_label}}
spec:
  selector:
    matchLabels:
      name: {{.Values.pv_label}} 
      tier: be
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
