apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc-{{.Values.pv_label}}

      containers:
      - image: bitnami/mariadb:latest
        name: mariadb
        volumeMounts:
        - name: mariadb-storage
          mountPath: /bitnami/mariadb/data
        env:
        - name: MARIADB_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: username
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: db_name
