apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-{{.Values.pv_label}}
  labels:
    name: {{.Values.pv_label}} 
    tier: be
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.nfs_mariadb_path}} 
