apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-{{.Values.pv_label}}
spec:
  selector:
    matchLabels:
      name: {{.Values.pv_label}}
      tier: fe
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
