apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{.Values.pv_label}}
  labels:
    name: {{.Values.pv_label}} 
    tier: fe
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.nfs_wordpress_path}} 
